dist: trusty
sudo: false
bundler_args: --without extras
# before_script:
#   - bundle exec rake core:verify
branches:
  only:
    - master
cache:
  bundler: true
services:
  - redis-server
script: bundle exec rake
rvm:
  - 2.3.5
  - 2.4.2
  - 2.5
  - 2.6
  - 2.7
